services:
  discord-bot:
    build: .
    image: ryu-bot
    env_file:
      - .env
    volumes:
      - ./database:/bot/src/database
      - ./discord.log:/bot/discord.log

    restart: unless-stopped